# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/sweet-misound/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter sweet,$(TARGET_DEVICE)),)

endif
